"use client";

import { Bot, TriangleAlert } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { cn } from "@/lib/utils";
import type { GenerationMeta } from "@/lib/types";

type LlmStatus = {
  mode: "live" | "fallback";
  provider: string;
  model: string;
  configured: boolean;
};

export const LLM_ACTIVITY_EVENT = "move-llm-activity";

/**
 * Tell the header badge about the latest generation result so it updates
 * immediately after a module call instead of waiting for the next poll.
 */
export function reportLlmActivity(generation?: GenerationMeta) {
  if (typeof window === "undefined" || !generation) return;
  window.dispatchEvent(new CustomEvent(LLM_ACTIVITY_EVENT, { detail: generation }));
}

export function LlmStatusBadge() {
  const [status, setStatus] = useState<LlmStatus | null>(null);

  const refresh = useCallback(async () => {
    try {
      const response = await fetch("/api/llm/status");
      if (!response.ok) return;
      setStatus(await response.json());
    } catch {
      // Leave the previous reading in place; the badge never blocks the UI.
    }
  }, []);

  useEffect(() => {
    const initial = window.setTimeout(() => {
      void refresh();
    }, 0);
    const onActivity = (event: Event) => {
      const generation = (event as CustomEvent<GenerationMeta>).detail;
      setStatus((current) =>
        current
          ? { ...current, mode: generation.mode === "llm" ? "live" : "fallback" }
          : current,
      );
      void refresh();
    };
    window.addEventListener(LLM_ACTIVITY_EVENT, onActivity);
    return () => {
      window.clearTimeout(initial);
      window.removeEventListener(LLM_ACTIVITY_EVENT, onActivity);
    };
  }, [refresh]);

  const live = status?.mode === "live";

  return (
    <span
      title={
        status
          ? live
            ? `Connected to ${status.provider} (${status.model})`
            : status.configured
              ? "An LLM key is set but the last call failed. Outputs use local fallback logic."
              : "No LLM key configured. Outputs use local fallback logic."
          : "Checking AI status"
      }
      className={cn(
        "inline-flex min-h-10 items-center gap-2 rounded-md border px-3 text-sm font-bold",
        live
          ? "border-green/45 bg-green/12 text-green-ink"
          : "border-warn/45 bg-warn/12 text-warn",
      )}
    >
      {live ? <Bot className="h-4 w-4" /> : <TriangleAlert className="h-4 w-4" />}
      {status ? (live ? "Live AI" : "Fallback mode") : "AI status..."}
      <span className={cn("h-2 w-2 rounded-full", live ? "bg-green" : "bg-warn", !status && "animate-pulse")} />
    </span>
  );
}

/**
 * Per-output provenance line. Every generated artifact shows one of these so
 * nobody mistakes fallback output for the LLM in a live demo.
 */
export function GenerationFooter({ generation }: { generation?: GenerationMeta | null }) {
  if (!generation) return null;
  const live = generation.mode === "llm";
  return (
    <p
      className={cn(
        "mt-4 flex items-center gap-2 rounded-md border px-3 py-2 text-xs font-semibold",
        live ? "border-green/35 bg-green/10 text-green-ink" : "border-warn/40 bg-warn/10 text-warn",
      )}
    >
      {live ? <Bot className="h-3.5 w-3.5 shrink-0" /> : <TriangleAlert className="h-3.5 w-3.5 shrink-0" />}
      {live
        ? `Generated by Live AI (${generation.provider}${generation.model ? ` · ${generation.model}` : ""})`
        : `Local fallback logic, not the LLM. ${generation.reason ?? ""}`}
    </p>
  );
}
